---
- name: tomcat user 
  template:
      dest: /opt/tomcat/conf/tomcat-users.xml
      src:  templates/mytomuser.j2


- name: copy manager context into node side
  template:
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml
      src: templates/mytommanager.j2

- name: copy host manager context into node side
  template:
      dest:  /opt/tomcat/webapps/host-manager/META-INF/context.xml
      src: templates/mytomHostmanager.j2